### ISSUE TITLE
RSpec 3 - backtrace_clean_patterns

### ISSUE THREAD

**Issue by JIAZHEN** [sandro/specjour#61]
When I try to use specjour, I'm getting

```
Workers ready: 4
Listening for qa-automation
rsync -aL --delete --ignore-errors --port=23456 192.168.50.79::qa-automation /private/tmp/qa-automation... completed in 13.986203s
before_fork... completed in 0.520666s
/Users/xxx/Documents/qa-automation/.bundle/gems/specjour-0.7.0/lib/specjour/rspec/runner.rb:2:in `<module:Runner>': undefined method `backtrace_clean_patterns' for #<RSpec::Core::Configuration:0x007fa8ca133920> (NoMethodError)
    from /Users/xxxx/Documents/qa-automation/.bundle/gems/specjour-0.7.0/lib/specjour/rspec/runner.rb:1:in `<top (required)>'
    from /Users/xxxx/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/xxxx/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/xxxx/Documents/qa-automation/.bundle/gems/specjour-0.7.0/lib/specjour/rspec.rb:10:in `<module:RSpec>'
    from /Users/xxxx/Documents/qa-automation/.bundle/gems/specjour-0.7.0/lib/specjour/rspec.rb:2:in `<module:Specjour>'
    from /Users/xxxx/Documents/qa-automation/.bundle/gems/specjour-0.7.0/lib/specjour/rspec.rb:1:in `<top (required)>'
    from /Users/xxxx/Documents/qa-automation/.bundle/gems/specjour-0.7.0/lib/specjour/loader.rb:84:in `load_app'
```

Could anyone help please? Thank you!

**Comment by hakunin** [comment]
This was first result on google unfortunatley.

The name has been changed to `backtrace_exclusion_patterns` here:
https://github.com/rspec/rspec-rails/pull/732/files
